apiVersion: v1
kind: Service
metadata:
  name: appointments
  namespace: e-sihha
spec:
  type: ClusterIP
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
