version: '3.8'

services:
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: production
    ports:
      - "3002:3000"
    env_file:
      - .env
  mongodb:
    image: mongo:6.0
    container_name: mongodb-medical-records
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: medical-records
      MONGO_URI: mongodb://mongodb:27017/medical-records
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: