apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: e-sihha
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: youssefar22/users:latest
          imagePullPolicy: Always
          env:
           envFrom:
            - configMapRef:
                name: users-config
            - secretRef:
                name: e-sihha-secrets
          ports:
            - containerPort: 3000
              protocol: TCP
          #readinessProbe:
            #httpGet:
              #path: /ping
              #port: 3000
          resources:
            limits:
              memory: "100Mi"
            requests:
              memory: "100Mi"
              cpu: "50m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
