apiVersion: v1
kind: Service
metadata:
  name: my-rabbitmq
  namespace: e-sihha
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: my-rabbitmq
