apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: e-sihha
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 443
      targetPort: 3000
      protocol: TCP
      name: https
  # Optional: specify loadBalancerIP if you have a static IP
  # loadBalancerIP: "YOUR_STATIC_IP"