apiVersion: v1
kind: Service
metadata:
  name: symptom-checker
  namespace: e-sihha
spec:
  type: ClusterIP
  selector:
    app: symptom-checker
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
