apiVersion: v1
kind: Service
metadata:
  name: my-postgres
  namespace: e-sihha
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: my-postgres
