apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: e-sihha
spec:
  type: ClusterIP
  selector:
    app: notifications
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
