apiVersion: v1
kind: Service
metadata:
  name: medical-records
  namespace: e-sihha
spec:
  type: ClusterIP
  selector:
    app: medical-records
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
