name: CI Build & Publish Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      users: ${{ steps.filter.outputs.users }}
      medical-records: ${{ steps.filter.outputs.medical-records }}
      appointments: ${{ steps.filter.outputs.appointments }}
      doctor: ${{ steps.filter.outputs.doctor }}
      notifications: ${{ steps.filter.outputs.notifications }}
      symptom-checker: ${{ steps.filter.outputs.symptom-checker }}
      api-gateway: ${{ steps.filter.outputs.api-gateway }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Detect changed services
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            users:
              - 'apps/users/**'
            medical-records:
              - 'apps/medical-records/**'
            appointments:
              - 'apps/appointments/**'
            doctor:
              - 'apps/doctor/**'
            notifications:
              - 'apps/notifications/**'
            symptom-checker:
              - 'apps/symptom-checker/**'
            api-gateway:
              - 'apps/api-gateway/**'
            
  users:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.users == 'true' }}
    uses: ./.github/workflows/microservice_ci_template.yml
    with:
      service-name: users
      service-dir: apps/users
      dockerfile-path: ./apps/users/Dockerfile
    secrets: inherit

  medical-records:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.medical-records == 'true' }}
    uses: ./.github/workflows/microservice_ci_template.yml
    with:
      service-name: medical-records
      service-dir: apps/medical-records
      dockerfile-path: ./apps/medical-records/Dockerfile
    secrets: inherit
  appointments:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.appointments == 'true' }}
    uses: ./.github/workflows/microservice_ci_template.yml
    with:
      service-name: appointments
      service-dir: apps/appointments
      dockerfile-path: ./apps/appointments/Dockerfile
    secrets: inherit
  doctor:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.doctor == 'true' }}
    uses: ./.github/workflows/microservice_ci_template.yml
    with:
      service-name: doctor
      service-dir: apps/doctor
      dockerfile-path: ./apps/doctor/Dockerfile
    secrets: inherit
  notifications:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.notifications == 'true' }}
    uses: ./.github/workflows/microservice_ci_template.yml
    with:
      service-name: notifications
      service-dir: apps/notifications
      dockerfile-path: ./apps/notifications/Dockerfile
    secrets: inherit
  symptom-checker:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.symptom-checker == 'true' }}
    uses: ./.github/workflows/microservice_ci_template.yml
    with:
      service-name: symptom-checker
      service-dir: apps/symptom-checker
      dockerfile-path: ./apps/symptom-checker/Dockerfile
    secrets: inherit
  api-gateway:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.api-gateway == 'true' }}
    uses: ./.github/workflows/microservice_ci_template.yml
    with:
      service-name: api-gateway
      service-dir: apps/api-gateway
      dockerfile-path: ./apps/api-gateway/Dockerfile
    secrets: inherit